### ISSUE TITLE
A mysterious button appears when viewing a photo

### ISSUE THREAD

**Issue by katacarbix** [Dr-TSNG/TwiFucker#1]
![Screenshot_20220208-142748.png](https://user-images.githubusercontent.com/1340784/153070204-6515a9b8-93dc-448b-86a0-1aaaf43f701a.png)

As you can see, there's a grey circle in the UI right above the reply button. This looks like a button and animates when pressed but does nothing as far as I can tell. It's not there when TwiFucker is turned off.

For reference:
- API version 93
- LSPosed framework/manager 1.7.2 (6379)
- Android 12
- Twitter app version 9.27.0-release.0

**Comment by katacarbix** [comment]
It appears in videos too actually

![Screenshot_20220208-194429.png](https://user-images.githubusercontent.com/1340784/153106160-ccd22ec7-9e38-424f-b813-18d80989ac51.png)

**Comment by Dr-TSNG** [comment]
Strange, I'll try to fix

**Comment by Dr-TSNG** [comment]
Fixed
