### ISSUE TITLE
Where do i see twifucker version in the app? Don't want Toast message

### ISSUE THREAD

**Issue by anyujinie** [Dr-TSNG/TwiFucker#102]
### Is your feature request related to a problem？
Yes.

Also I sent a join request to the telegram Discussion Group but nobody accepts it

**Comment by kobitate** [comment]
[RTFM](https://github.com/Dr-TSNG/TwiFucker#Usage)

**Comment by anyujinie** [comment]
@JasonKhew96 Lol what? I asked a question regarding where I can see twifucker version inside the app. Nobody answered it.

Also I asked why join requests to discussion group are not accepted?

**Comment by JasonKhew96** [comment]
> @JasonKhew96 Lol what? I asked a question regarding where I can see twifucker version inside the app? Nobody answered it.
> 
> Also I asked why join requests to discussion group are not accepted?

@anyujinie Add version number in settings dialog later, if you don't want Toast you can turn if off in settings.
The join requests processing bot is having issues yesterday, probably fixed today, you can try to apply.

**Comment by anyujinie** [comment]
Ok looking forward to seeing twifucker version number inside app soon 👌🏻

I'll send another join request then. Thx for answering 🙏🏻

**Comment by anyujinie** [comment]
@JasonKhew96 Still haven't been accepted into the group. Can you add me manually please?
