### ISSUE TITLE
Twifucker keeps removing 'custom app icon' (Twitter Blue Feature)

### ISSUE THREAD

**Issue by anyujinie** [Dr-TSNG/TwiFucker#103]
### Steps to reproduce/复现步骤

I pay for Twitter Blue and use the custom app icon feature. Every time I start twifucker/twitter the custom app color gets reset to default color. Please fix this. 

![Screenshot_20230130-140856364 (1)](https://user-images.githubusercontent.com/73917917/215486470-c75dd193-68e4-4fa2-a791-61a50dd2adb8.jpg)

![Screenshot_20230130-140002181 (1)](https://user-images.githubusercontent.com/73917917/215485135-5fc830e0-893d-49f2-adac-839a066a5f5c.jpg)

### Expected behaviour/预期行为

Don't reset custom app color!

### Actual behaviour/实际行为

x

### Xposed Module List/Xposed 模块列表

```Shell
x
```

### TwiFucker version/TwiFucker 版本

Latest todays release 

### Twitter version/Twitter 版本

9.730

### Android version/Android 版本

12

### Xposed Framework/Xposed 框架

LSPosed

### Framework version/框架版本

x

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

x

**Comment by JasonKhew96** [comment]
confirmed it's Twitter client problem
