### ISSUE TITLE
[Join request Telegram discussion group] What is this captcha? I am not a scientist to understand this

### ISSUE THREAD

**Issue by anyujinie** [Dr-TSNG/TwiFucker#106]
Are you guys trolling? What's this supposed to be? I'm not a scientist to understand and solve this...
I literally only want to join the discussion group.

![Screenshot_20230131-014924415](https://user-images.githubusercontent.com/73917917/215630879-b2e5e855-cf4b-4471-8760-7e765d1f7766.png)

**Comment by JasonKhew96** [comment]
check Telegram Channel description, there is an invite link without admin approval

**Comment by anyujinie** [comment]
Idk the link is not working? I put it in Google and telegram and doesn't work.
Can you add me to the group? My username is AnYujin1 

Please. How difficult can it be to join a group.

**Comment by justbearcause** [comment]
> check Telegram Channel description, there is an invite link without admin approval

The invitation link is expired.

**Comment by iBasim** [comment]
me 2 i can't join I don't know what you want to verify
