### ISSUE TITLE
What do all these experimental flags do??

### ISSUE THREAD

**Issue by anyujinie** [Dr-TSNG/TwiFucker#107]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Anybody can please explain maybe with screenshots what these flags change in the app? Saw them in the telegram flags channel

account_teams_enabled: false
ad_formats_instream_redesign_android_enabled: true
ad_formats_use_video_element_for_cards_scribing: false
af_ui_chirp_enabled: false
af_ui_chirp_enabled: true
af_ui_vdl_m2_remove_timeline_module_dividers_enabled: true
alt_text_for_gifs_enabled: true
android_async_inflation_enabled: true
android_async_video_player_view_enabled: true
android_audio_room_creation_enabled: true
android_audio_room_nux_tooltips_ignore_fatigue: false
android_audio_room_nux_tooltips: true
android_audio_room_replay_enabled: true
android_audio_share_listening_with_followers_setting_enabled: true
android_audio_space_amplitude_enabled: true
android_audio_spaces_device_follow_api_enabled: false
android_audio_spaces_device_follow_api_enabled: true
android_audio_spaces_device_follow_user_api_enabled: true
android_audio_spaces_tab_enabled: false
android_audio_tweets_consumption_enabled: false
android_audio_voice_info_consumption_enabled: false
android_auto_drafting_enabled: false
android_behavioral_events_ceol_allowlist_filter_enabled: true
android_collect_database_perf_counter_metrics: false
android_collect_database_perf_metrics: false
android_collect_notifications_perf_metrics: false
android_compose_fab_menu_enabled: true
android_disable_offline_retries: false
android_disable_offline_retries: true
android_error_reporter_cursor_window_refill_enabled: false
android_expose_alt_text_enabled: true
android_fleets_expanded_spacebar_items_enabled: false
android_gif_hashtag_highlight_is_enabled: false
android_graphql_home_timeline_enabled: false
android_hashflags_service_api_enabled: true
android_hls_url_additional_query_parameter_enabled: true
android_htl_position_metadata_capture_enabled: false
android_hydra_media_player_enabled: false
android_initializer_refactor_report_pct_trace: false
android_media_keyboard_enabled: true
android_media_playback_skip_ad_enabled: true
android_mediaplayer_audio_only_playback_enabled: false
android_mediaplayer_metric_ticking_playback_150_enabled: false
android_mediaplayer_metric_ticking_playback_50_enabled: false
android_mediaplayer_metric_ticking_playback_enabled: true
android_mixed_media_badges_enabled: false
android_new_vod_audio_toggle_enabled: false
android_optimize_position_restoration_lookup: false
android_pct_enabled: true
android_recycler_view_scope_release_enabled: true
android_refactor_background_blocking_initializers_init_fresco_asynchronously: true
android_remove_webview_initialization_enabled: true
android_schema_checker_enabled: false
android_soft_intervention_tweet_disable_autoplay_enabled: true
android_telephonyutil_networkcallback_enabled: false
android_timeline_void_orphaned_items_enabled: true
android_tweet_deamplification_transparent_cursors_enabled: false
android_tweet_detail_refactor_enabled: true
android_tweet_promote_button_enabled: true
android_urt_geo_enabled: false
android_video_ad_calc_overlap_alg_enabled: false
android_video_analytics_pcomplete_enabled: true
android_video_analytics_scribe_thrift_construction_required_enabled: false
android_video_analytics_system_volume_provider_enabled: true
app_event_track_non_referred_open_enabled: true
app_rating_prompt_enable: true
app_rating_prompt_show_now: false
author_moderated_replies_author_enabled: true
author_moderated_replies_consumer_enabled: true
auth_timeline_token_tracking_enabled: true
awards_send_button_enabled: false
b2c_dm_custom_keyboard_adaptive_height_enabled: true
birdwatch_consumption_enabled: false
compose_highlight_entities_enabled: true
consideration_lonely_birds_good_impression_android_share_at_end_enabled: false
consideration_sso_fetch_user_connections: true
contextv2_plus_projectnah_context_enabled: false
contextv2_plus_projectnah_dismiss_enabled: false
conversational_replies_android_author_label_microphone_enabled: false

### Describe the solution you'd like/描述你想要的解决方案

x

**Comment by JasonKhew96** [comment]
nothing to do with us, those flags are built-in inside Twitter application, some of them might remove in future
