### ISSUE TITLE
It's completely impossible for me to load the telegram group captcha

### ISSUE THREAD

**Issue by MKCOOL142** [Dr-TSNG/TwiFucker#108]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Your website seems slow and my wifi just makes it worse, either I get a cloudflare error or stuck loading forever 
![Screenshot_20230202-221654](https://user-images.githubusercontent.com/40364718/216455569-659e9781-d0d2-484d-bb73-e8581ecfa3f5.png)
![Screenshot_20230202-223349](https://user-images.githubusercontent.com/40364718/216455558-8e22e261-69e1-4c4c-93cb-58f22c14be8a.png)

![Screenshot_20230202-223448](https://user-images.githubusercontent.com/40364718/216455542-232a7d9a-8f9c-44b0-819d-1bf8ef41a577.png)
![Screenshot_20230202-223517_OwlGram](https://user-images.githubusercontent.com/40364718/216455518-82e24e43-a864-4b71-ad78-4904c9232ed7.png)

### Describe the solution you'd like/描述你想要的解决方案

Can you please add me manually, @Mattis142 on telegram thank you

**Comment by MKCOOL142** [comment]
![Screenshot_20230202-225007](https://user-images.githubusercontent.com/40364718/216460710-4bff0242-fa2b-4549-97e4-13494890918d.png)
Bro 😭☠️

**Comment by JasonKhew96** [comment]
check Telegram Channel description, there is an invite link without admin approval
