### ISSUE TITLE
[Twitter's Feature Request] 

### ISSUE THREAD

**Issue by TheGoldenSun** [Dr-TSNG/TwiFucker#113]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No.

### Describe the solution you'd like/描述你想要的解决方案

I have a question, is it possible for users to edit tweet, post longer video uploads with good quality, use reader, custom navigation, bookmark folders, undo tweet, and rocket to the top of replies mentions and search on Twitter? 

### Additional context/其他信息

I've been wondering about it since editing a tweet along with other features that's useful maybe an interesting feature to use.

**Comment by JasonKhew96** [comment]
https://help.twitter.com/en/using-twitter/twitter-blue
