### ISSUE TITLE
[Feature Request] download quality selection

### ISSUE THREAD

**Issue by retalsnake** [Dr-TSNG/TwiFucker#115]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Add download quality selection option

### Describe the solution you'd like/描述你想要的解决方案

Add download quality option like resolutions 

### Additional context/其他信息

![Screenshot_2023-02-15-14-56-16-600_com twitter android](https://user-images.githubusercontent.com/125451885/218994807-b9a5a2e5-bfd9-44e8-9b35-4c66f24b72c0.jpg)
This screeshot describe what exatly what feature i requirest

**Comment by JasonKhew96** [comment]
I don't see the point of downloading lower quality of media.
