### ISSUE TITLE
[Twitter Bug] 

### ISSUE THREAD

**Issue by TheGoldenSun** [Dr-TSNG/TwiFucker#116]
### Steps to reproduce/复现步骤

1. Open telegram
2. Update to a debug version
3. Once it's installed check to see if the version is bumped.

### Expected behaviour/预期行为

Users should be able to uninstall and update newer debug version over the oldest versions that was released from telegram. 

### Actual behaviour/实际行为

Tried installing the debug version V1.9.r196.4594f45-debug.apk from telegram on my armeabi-v7a device from telegram all it told me is to update the version which I did for 9.74.0 but it turns out that it's still when launching on the app it automatically tells me that I'm still on version 1.9.r194.5c23ea0 not V1.9.r196.4594f45-debug.apk 

I hope someone is able to resolve this issue. 

### Xposed Module List/Xposed 模块列表

```Shell
Exposed Module: SM-S124DL

Android Version: 12 

CPU version: armeabi-v7a (Arm 7)
```

### TwiFucker version/TwiFucker 版本

V1.9.r196.4594f45-debug.apk

### Twitter version/Twitter 版本

9.74.0

### Android version/Android 版本

Galaxy a02 - arm 7 

### Xposed Framework/Xposed 框架

LSPatch

### Framework version/框架版本

0aaa533

### Version requirement/版本要求

Version required by the developer/开发者要求的版本

### Logs/日志

N/A

**Comment by JasonKhew96** [comment]
embedded mode won't work, you need to repackage Twitter apk with new version of TwiFucker module
or you can use LSPatch Manager to manage module without embedding TwiFucker module into apk (still need to patch it with LSPatch), but this mode requires Manager to run in background
