### ISSUE TITLE
[Bug] Unable to like tweets in media view mode

### ISSUE THREAD

**Issue by Gnbrkm41** [Dr-TSNG/TwiFucker#117]
### Steps to reproduce/复现步骤

1. Click any media in a tweet (e.g. image / video). Observe that the media is enlarged to fullscreen mode.
2. Try adding the tweet to favourites by clicking the heart icon.

### Expected behaviour/预期行为

The heart icon turns red and stays red. The said tweet should be visible in the list of favourited tweets.

### Actual behaviour/实际行为

The heart icon turns red for a brief moment before it goes back to being unfavourited. The said tweet is not visible in favourited tweets.

### Xposed Module List/Xposed 模块列表

```Shell
I just download the non-root patched APK from Telegram, so I'm not exactly sure about all the infos listed below. The description of the file says:

LSPatched from 29740000
9.74.0-release.0
TwiFucker: 5c23ea0
LSPatch: 0aaa533
```

### TwiFucker version/TwiFucker 版本

1.9.r194.5c23ea0 (194)

### Twitter version/Twitter 版本

9.74.0-release.0

### Android version/Android 版本

13

### Xposed Framework/Xposed 框架

LSPatch

### Framework version/框架版本

Not sure?

### Version requirement/版本要求

Other/其他

### Logs/日志

Log exported from TwiFucker's settings menu: [log (1).txt](https://github.com/Dr-TSNG/TwiFucker/files/10773747/log.1.txt)

**Comment by JasonKhew96** [comment]
reproduced without module enabled
