### ISSUE TITLE
[Bug] full width media feature switch does not work

### ISSUE THREAD

**Issue by Pratik-193** [Dr-TSNG/TwiFucker#120]
### Steps to reproduce/复现步骤

media_edge_to_edge_content_enabled feature switch does not work since the last couple of versions.

### Expected behaviour/预期行为

photos and videos in tweets should be visible in full width

### Actual behaviour/实际行为

Original behavious as stock twitter app

### Xposed Module List/Xposed 模块列表

```Shell
NA
```

### TwiFucker version/TwiFucker 版本

1.9.r209.7d270fb (209)

### Twitter version/Twitter 版本

9.78.0-release.0

### Android version/Android 版本

13

### Xposed Framework/Xposed 框架

LSPosed

### Framework version/框架版本

1.9.r209.7d270fb (209)

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

no logs required

**Comment by JasonKhew96** [comment]
Twitter remove that switch long time ago (Twitter Alpha)
