### ISSUE TITLE
[Feature Request]  Turkish language update

### ISSUE THREAD

**Issue by serkanege** [Dr-TSNG/TwiFucker#122]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Turkish language update.

### Describe the solution you'd like/描述你想要的解决方案

I translated the missing lines in the language file, could you please update it?
Tahnks.

### Additional context/其他信息

**Comment by serkanege** [comment]
[strings.xml](https://mega.nz/file/GhUDlKQb#p_eBNfBhOZqzRCbOknP_k9x5mYTaWYQz0z7jDwl_rgw)

**Comment by cracky5322** [comment]
You should use "Pull requests" to submit

**Comment by JasonKhew96** [comment]
#123
