### ISSUE TITLE
[Feature Request] Selectable text in timeline

### ISSUE THREAD

**Issue by iLikeCake10** [Dr-TSNG/TwiFucker#127]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Having to open tweet details every time to copy text of a tweet is a bit inconvenient.

### Describe the solution you'd like/描述你想要的解决方案

Implement ability to copy text in timeline.

**Comment by JasonKhew96** [comment]
This feature will likely breaks other feature such as open tweet details, no
