### ISSUE TITLE
[Feature Request] 提供移除For you界面的选项

### ISSUE THREAD

**Issue by rayseoi** [Dr-TSNG/TwiFucker#130]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Twitter 目前开屏后只能显示For you页面，如果只想看自己的follow 的内容需要右滑，非常不方便。

### Describe the solution you'd like/描述你想要的解决方案

提供一个能移除for you页面的选项，开屏默认是follow的内容

**Comment by JasonKhew96** [comment]
官方支持记住上一次选择 (For you/Following)
不记得哪个版本启用了，老版本得 Feature Switch `home_timeline_spheres_sticky_tabs_enabled`

还没找到完全移除 For you 页面的方法

**Comment by Mogez** [comment]
+1

非常想要这个，for you 太讨厌～

**Comment by yingshaoxo** [comment]
+1

**Comment by JasonKhew96** [comment]
https://github.com/Dr-TSNG/TwiFucker/issues/112
