### ISSUE TITLE
[Feature Request]  Download GIF images without conversion to MP4

### ISSUE THREAD

**Issue by A-of-Wonder** [Dr-TSNG/TwiFucker#131]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Currently, GIF images are downloaded with conversion to MP4. However, files converted from GIF cannot be opened.

### Describe the solution you'd like/描述你想要的解决方案

Download GIF images in their original format without conversion.

**Comment by JasonKhew96** [comment]
There is no GIF link, you can't download GIF format.
