### ISSUE TITLE
[Feature Request] About downloading GIFs

### ISSUE THREAD

**Issue by lichi7887** [Dr-TSNG/TwiFucker#135]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

When I download a GIF image, it is saved as an MP4 file by mistake(maybe mistake?I am not sure)

### Describe the solution you'd like/描述你想要的解决方案

I hope to be able to download real GIF images in a later version.Thank you very much for developing this xposed module

**Comment by JasonKhew96** [comment]
any GIF uploaded to Twitter will get converted into no sound MP4, there is no GIF to download
