### ISSUE TITLE
中文翻译[Feature Request] 

### ISSUE THREAD

**Issue by Ehoumaki** [Dr-TSNG/TwiFucker#143]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

多久能补全下中文翻译，功能越来越全，没翻译的地方也越来越多。

### Describe the solution you'd like/描述你想要的解决方案

中文翻译全

**Comment by Dr-TSNG** [comment]
这种问题应该提pr而不是issue

**Comment by Ehoumaki** [comment]
怎么提不会呀
