### ISSUE TITLE
[Bug] Incorrect control flow for disabling "Who to follow"

### ISSUE THREAD

**Issue by oSumAtrIX** [Dr-TSNG/TwiFucker#154]
### Issue

If `disable_who_to_follow` is true, the setting `disable_promoted_user` has no effect because control flow is blocked:
https://github.com/Dr-TSNG/TwiFucker/blob/master/app/src/main/java/icu/nullptr/twifucker/hook/JsonHook.kt#L302

**Comment by JasonKhew96** [comment]
but the promoted user is in the who to follow module(?)

**Comment by oSumAtrIX** [comment]
What do you mean by that? I am referring to this:

![image](https://github.com/Dr-TSNG/TwiFucker/assets/13122796/1d1e44e5-35c6-47b7-94a4-403e7c2a3863)

**Comment by JasonKhew96** [comment]
removing who to follow also removes promoted users and normal user

promoted users usually exist in who to follow module at first item

![IMG_20230520_104333.jpg](https://github.com/Dr-TSNG/TwiFucker/assets/29531167/23bac22e-05b9-4ff2-acfa-a083a7e83e70)

red: who to follow module
green: promoted user (example)
