### ISSUE TITLE
sensible download name

### ISSUE THREAD

**Issue by Turhvjbufv** [Dr-TSNG/TwiFucker#161]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Currently you have no way to know which twitter user the download came from(at least not easily).

### Describe the solution you'd like/描述你想要的解决方案

Then could you please make the image take the username and maybe the tweet title and name that the image?

**Comment by JasonKhew96** [comment]
https://github.com/Dr-TSNG/TwiFucker/issues/114
