### ISSUE TITLE
[FEATURE] Unlimited posts to view

### ISSUE THREAD

**Issue by K-plus69** [Dr-TSNG/TwiFucker#163]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Yes. Twitter made a restriction to only allow a set number of posts to view a day. 

### Describe the solution you'd like/描述你想要的解决方案

To block the code that tells the server how many posts you read.

### Additional context/其他信息

Elon musk wrote this. Works on any version

**Comment by JasonKhew96** [comment]
server side, you can change to any other platform to bypass restrictions per account.
