### ISSUE TITLE
How do I open the module settings? 

### ISSUE THREAD

**Issue by Lucky-069** [Dr-TSNG/TwiFucker#17]
I can't find out the option to open module settings. It isn't even available in the lsposed settings too. I just get a toast that says twifucker v

**Comment by JasonKhew96** [comment]
It's hidden inside `Settings` --> `Additional resources` --> `Version`
~~haven't found a way to inject menu...~~

**Comment by Lucky-069** [comment]
Got it thank you!  :) Also I have been getting news recommendations and post recommendations randomly, can that be closed aswell?

**Comment by Lucky-069** [comment]
Got it! Thanks

**Comment by JasonKhew96** [comment]
> Got it thank you! :) Also I have been getting news recommendations and post recommendations randomly, can that be closed aswell?

Can't reproduce, those recommendations probably cached before TwiFucker activated and I have no idea how to clear those kind of cache gracefully, Twitter code is obfuscated heavily.
