### ISSUE TITLE
ads are still showing in comments

### ISSUE THREAD

**Issue by TeaqariaWTF** [Dr-TSNG/TwiFucker#22]
Poco X3
Android 12.1
TwiFucker 1.3
Magisk 24.5
Lsposed 1.8.3 (6574)
Twitter  9.46.0-release.0

![Screenshot_20220619-122541_Twitter](https://user-images.githubusercontent.com/90970076/174474591-0d48c9b6-a72a-481f-9807-8bbe4651aa57.png)

Lsposed log : https://gofile.io/d/iwFUMM

**Comment by JasonKhew96** [comment]
duplicate https://github.com/Dr-TSNG/TwiFucker/issues/19
