### ISSUE TITLE
Promoted tweets issue 

### ISSUE THREAD

**Issue by AhmedPie** [Dr-TSNG/TwiFucker#28]
There are promoted tweets in replies to tweets.

![IMG_20220712_025551.jpg](https://user-images.githubusercontent.com/79719273/178377877-c7e6be6e-dfad-4aea-bdb5-7d0b75ee9a15.jpg)

**********
Phone: Realme GT 5G
Android Version: 12
TwiFucker Version: 1.3
LSPatch Version: 0.3.1
Twitter Version: 9.49
**********

**Comment by JasonKhew96** [comment]
https://github.com/Dr-TSNG/TwiFucker/issues/19
