### ISSUE TITLE
Sensitive Media Warning issue

### ISSUE THREAD

**Issue by AhmedPie** [Dr-TSNG/TwiFucker#29]
The option:
Disable Sensitive Media Warning.

Is not working in "Twitter Communities"

![Screenshot_2022-07-12-03-06-40-26_0b2fce7a16bf2b728d6ffa28c8d60efb.jpg](https://user-images.githubusercontent.com/79719273/178379428-351d7466-bd18-4b9a-8008-654dee2098da.jpg)
![Screenshot_2022-07-12-03-10-01-95_0b2fce7a16bf2b728d6ffa28c8d60efb.jpg](https://user-images.githubusercontent.com/79719273/178379455-dc13b0fb-7a77-48c1-a99c-f5ad315f1873.jpg)

**********
Phone: Realme GT 5G
Android Version: 12
TwiFucker Version: 1.3
LSPatch Version: 0.3.1
Twitter Version: 9.49
**********

**Comment by JasonKhew96** [comment]
I have no idea where is it, is there a link or step to access this page?

**Comment by AhmedPie** [comment]
> I have no idea where is it, is there a link or step to access this page?

You can join any Twitter community, like this one:
https://twitter.com/i/communities/1509149242224672770
