### ISSUE TITLE
TwiFucker is broken on 9.53.0-release.0

### ISSUE THREAD

**Issue by subby2006** [Dr-TSNG/TwiFucker#36]
Ads are appearing on the timeliness after the new update. Haven't seen any ads in the trends page but probably because it's too early here for Twitter to show ads on the trends. No dialog box was shown on first launch and the toast on spash wasn't shown either. Dialog box is inaccessible from the settings, instead only copies the build number of the app. Please fix

**Comment by aliafshany** [comment]
exactly
i updated my Twitter and now this happens.
i also downloaded the last app from the channel
