### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Lucky-069** [Dr-TSNG/TwiFucker#40]
Would it be possible for you to add a download option to any media. Just like aerotwitter has? 
![Screenshot_20220810-174414](https://user-images.githubusercontent.com/78787509/183898373-68183c81-0737-43bc-8edb-a61075bf8742.png)

**Comment by fatguy666** [comment]
> Would it be possible for you to add a download option to any media. Just like aerotwitter has? ![Screenshot_20220810-174414](https://user-images.githubusercontent.com/78787509/183898373-68183c81-0737-43bc-8edb-a61075bf8742.png)

I made a guide on patching AeroWitter with TwiFucker, don't see any ads with TwiFucker 1.4

https://www.reddit.com/r/moddedandroidapps/comments/wbud1e/aerowitter_twifucker_non_root_twitter_mod/

**Comment by Lucky-069** [comment]
I'm talking about the download option not the ad free

**Comment by fatguy666** [comment]
> I'm talking about the download option not the ad free

Yeah, I know. You get all the functionality of AeroWitter (download button) but with no ads. 

AeroWitter is an older version of Twitter 9.39 but TwiFucker 1.4 works fine on it.

**Comment by Lucky-069** [comment]
That is why I meant. There hasn't been aerowitter update. I want to bump to latest version of Twitter! Without having to wait manually.
