### ISSUE TITLE
[BUG] Twitter 9.56.X

### ISSUE THREAD

**Issue by JasonKhew96** [Dr-TSNG/TwiFucker#51]
Twitter 9.56.X breaks a lot of hook
- ~~Settings hook (Unable to open settings menu)~~ https://github.com/Dr-TSNG/TwiFucker/commit/dbda6fdcfe0cb89effe5cc1f0d87b6f2f982fef5
- Download hook (Unable to download)
- ~~JSON hook (Unable to remove promoted content, user and trends if legacy hook switch enabled)~~ https://github.com/Dr-TSNG/TwiFucker/commit/164fa9b9f1d02ca339f397dcd1d96c2713c50858

**Comment by aliafshany** [comment]
yes, i am using 9.56.1, and i confirm that.

-Settings hook (Unable to open settings menu)

only i get twifucker's pop up in the beginning, that's all

**Comment by aliafshany** [comment]
it's fixed for me
thank you

**Comment by Bec-de-Xorbin** [comment]
Seems like settings hook is broken again in 9.56.2 at least on rootless version.

Ps. What is the puropse of legacy JSON hook?

**Comment by fatguy666** [comment]
9.56.2 patched apk on telegram can't open TwiFucker settings (can see toast). 

Can't find any combo to of versions of Twitter + TwiFucker that gets rid of ads.
