### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by MKCOOL142** [Dr-TSNG/TwiFucker#54]
I saw that V1.4.r64.ce28680 contains the option to skip t.co redirects, would it also be possible to disable custom tabs entirely and just open the default browser? I would really appreciate that because to me using a full chrome experience is more useful

**Comment by JasonKhew96** [comment]
![IMG_20220828_190553.jpg](https://user-images.githubusercontent.com/29531167/187070924-4d01061c-9f6b-4109-a16b-f0b169b50c8c.jpg)
