### ISSUE TITLE
Auto shutdown on start.

### ISSUE THREAD

**Issue by IdhemS** [Dr-TSNG/TwiFucker#59]
Oppo f9 pro

**Comment by ianchb** [comment]
@IdhemS no log no fix, works on my machine

**Comment by IdhemS** [comment]
How to get the log?.

**Comment by IdhemS** [comment]
What logs ? Elaborate more, thank you.

**Comment by JasonKhew96** [comment]
@IdhemS 
- Android Version: ?
- Twitter Version: ?
- TwiFucker Version: ?
- Is LSPatched: ?
  - LSPatch Version: ?

What is auto shutdown? App crashed? Phone rebooted?

**Comment by IdhemS** [comment]
I downloaded the apk from telegram channel.

I think I messed up, ill check more if i can make it work, ill be greatful if i get some help.
 Thank you.

Android Version: 10
Twitter Version: 9.58.1-release-0
TwiFucker Version: latest on github
Is LSPatched: i dont know for sure it says it 
LSPatch Version: 
What is auto shutdown? = On start the app close by it self on every launche

**Comment by IdhemS** [comment]
I downloaded the apk from telegram channel.

I think I messed up, ill check more if i can make it work, ill be greatful if i get some help.
 Thank you.

 API Version
93

LSPatch Version
0.3.1 (308)

Framework Version
1.8.3 (6563)

System Version
10 (API 29)

Device
OPPO CPH1823 

System ABI
arm64-v8a

Twitter Version: 9.58.1-release-0
Is LSPatched: i dont know for sure it says it 

What is auto shutdown? = On start the app close by it self on every launche

**Comment by JasonKhew96** [comment]
Try latest `TwiFucker` CI Build from [HERE](https://github.com/Dr-TSNG/TwiFucker/actions/workflows/main.yml)
and if you want to patch `APK` yourself with LSPatch ([CI](https://github.com/LSPosed/LSPatch/actions/workflows/main.yml) / [Release](https://github.com/LSPosed/LSPatch/releases)), either using LSPatch Manager to patch it on Android or manually from PC.
You can get Twitter APK on apkmirror / apkpure / ~~[my drive](https://go.jasonkhew96.eu.org/0:/com.twitter.android/)~~
