### ISSUE TITLE
What is the recommended version?

### ISSUE THREAD

**Issue by j7b3y** [Dr-TSNG/TwiFucker#61]
As shown in #19 , Ver9.5x clients will display promotional tweets when displaying replies.
I was using it because it was not displayed in ver9.39, but one day I noticed that the Hook of the Download button was not working.
which version should i use?

**Comment by JasonKhew96** [comment]
if you want **experimental features**, **latest CI build** with **latest**  (or one version older) **stable** of Twitter client
