### ISSUE TITLE
[Bug] Promoted trends appear in trending topic

### ISSUE THREAD

**Issue by subby2006** [Dr-TSNG/TwiFucker#63]
### Steps to reproduce/复现步骤

1. Open Twitter LSPatch version
2. Ensure all ad removal settings are enabled
3. Go to search. You will see promoted trends

### Expected behaviour/预期行为

Promoted trends should not appear

### Actual behaviour/实际行为

Promoted trends appear. This started happening about a week and a half ago

### Xposed Module List/Xposed 模块列表

```Shell
Not Applicable (non-root)
```

### TwiFucker version/TwiFucker 版本

TwiFucker-V1.6.r87.814b66a-release

### Twitter version/Twitter 版本

9.61 release

### Android version/Android 版本

11

### Xposed Framework/Xposed 框架

LSPatch

### Framework version/框架版本

Not Applicable

### Version requirement/版本要求

Public release/beta version/公开发布/测试版

### Logs/日志

No option of lsposed manager in non-root so cannot take logs

**Comment by Dr-TSNG** [comment]
TwiFucker has built-in logger, you can export

**Comment by subby2006** [comment]
@Dr-TSNG how do you export logs from Twitter. I tried looking through the patch menu but no option of exporting logs
