### ISSUE TITLE
Ads are not blocked

### ISSUE THREAD

**Issue by GalaxyNight** [Dr-TSNG/TwiFucker#7]
Poco X3 Pro CrDroid8.2 Android12
Twitter : 9.33.0-release.0
Twifucker : 1.1

**Comment by GoodyOG** [comment]
When you enable the app module form lsposed, Select system framework and Twitter. Reboot.
wiring well on Twitter version 9.33.0-release.0, AEX A12

**Comment by GalaxyNight** [comment]
> When you enable the app module form lsposed, Select system framework and Twitter. Reboot. wiring well on Twitter version 9.33.0-release.0, AEX A12

Thank you very much!
I added the System framework and it works perfectly.

**Comment by Dr-TSNG** [comment]
@GoodyOG This module needn't hook system framework and will not take any effort on system framework. I think it's something bugging.

**Comment by Dr-TSNG** [comment]
Check 1.2

**Comment by rodrigoswz** [comment]
It was working well for me in v1.1, after upgrading to v1.2, I see ads everywhere 😔

![LSPosed and Twitter with Ads on feed](https://user-images.githubusercontent.com/14058427/159050091-6aad3ef1-13ee-4e31-865c-01725fed6c11.png)

![Module Settings](https://user-images.githubusercontent.com/14058427/159050508-28481527-739d-40be-8cc8-14c0361cbeaa.png)

- Xiaomi Mi 9T
- Android 12
- LSPosed 1.7.2
- Magisk 24.3

**Comment by Dr-TSNG** [comment]
LSPosed log needed

**Comment by rodrigoswz** [comment]
> LSPosed log needed

Sorry, here is:
https://send.vis.ee/download/83d72cb7e5af0a37/#Qw-rUIbsKtTdMCzxBtJ8gw

**Comment by Dr-TSNG** [comment]
Twitter version?

**Comment by rodrigoswz** [comment]
> Twitter version?

9.36.0-alpha.5

I think the alpha program has already closed. But you can get the apk here:
https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-36-0-alpha-5-release/

**Comment by Dr-TSNG** [comment]
@rodrigoswz We are still managing to implement dynamic hook. Currently alpha version is not supposed, you can back to stable version or wait us update

**Comment by Dr-TSNG** [comment]
Could you please try this version?
https://github.com/Dr-TSNG/TwiFucker/actions/runs/2005706365

**Comment by Dr-TSNG** [comment]
> > Twitter version?
> 
> 9.36.0-alpha.5
> 
> I think the alpha program has already closed. But you can get the apk here: https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-36-0-alpha-5-release/

Could you please try this version?
https://github.com/Dr-TSNG/TwiFucker/actions/runs/2005706365

**Comment by rodrigoswz** [comment]
> > > Twitter version?
> > 
> > 
> > 9.36.0-alpha.5
> > I think the alpha program has already closed. But you can get the apk here: https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-36-0-alpha-5-release/
> 
> Could you please try this version? https://github.com/Dr-TSNG/TwiFucker/actions/runs/2005706365

Thanks! Apparently this version is working very well with 9.36.0-alpha.5

I didn't find any ads in the feed or explore tab
