### ISSUE TITLE
[Bug] no download in v1.7 possible

### ISSUE THREAD

**Issue by Ranger2000** [Dr-TSNG/TwiFucker#71]
### Steps to reproduce/复现步骤

1. fresh install of "Twitter lspatched.apk with twifucker v1.7" from 16. October or newer from https://t.me/TwiFucker
2. enable the Download Hook in settings
3. klick the sharing button at a picture or video, and klick the download button
4. The Toast-info tells that the download was successful, but it was not

All previous lspatched Versions with twifucker v1.6 the Download Hook works fine

### Expected behaviour/预期行为
The download should work like before

### Actual behaviour/实际行为
The download does not work anymore at the lspatched versions since twifucker v1.7

### Xposed Module List/Xposed 模块列表
no xposed installed, only the lspatched apk used

### TwiFucker version/TwiFucker 版本
TwiFucker-V1.7.r110.941aef6-release

### Twitter version/Twitter 版本
9.63.0

### Android version/Android 版本
12

### Xposed Framework/Xposed 框架
Other

### Framework version/框架版本
no framework used

### Version requirement/版本要求
Public release/beta version/公开发布/测试版

### Logs/日志
[debug.log](https://github.com/Dr-TSNG/TwiFucker/files/9864216/debug.log)

**Comment by JasonKhew96** [comment]
Is your `/storage/emulated/0/Download` directory contains `TwiFucker` directory?
In recent change, I remove the need to select directory after download complete, instead download directly to `Download` directory.

**Comment by Ranger2000** [comment]
Many thanks for your help and explanation.
I always was searching in the `download` folder for the files.
The android media-manager had not indexed the Media files because another app has set .nomedia and .noindex.

Now I checked everything again, and it works fine.
Even if I delete the subfolder `twifucker`, it will be created again from `TwiFucker-App`

Therefore the ticked could be close.
