### ISSUE TITLE
[Feature Request] Differentiate official vs paid blue check

### ISSUE THREAD

**Issue by MikuDroid** [Dr-TSNG/TwiFucker#73]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No.

### Describe the solution you'd like/描述你想要的解决方案

Do you have a plan for implementing similar method as [eight dollars](https://github.com/wseagar/eight-dollars/raw/main/assets/example.png) or [tweak-new-twitter](https://user-images.githubusercontent.com/226692/201265207-9990092b-346b-4c9b-8c04-8d1ec461a482.gif)?

### Additional context/其他信息

Recent events of paid checkmarks is a mess imo.

**Comment by JasonKhew96** [comment]
https://twitter.com/Twitter/status/1601692772678762496
