### ISSUE TITLE
[Feature Request] Hide Spaces 'now live' bar in timeline

### ISSUE THREAD

**Issue by Narayana2195** [Dr-TSNG/TwiFucker#74]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Whenever someone you follow joined a Space, a 'now live' bar appears at the top of the timeline. This is annoying and redundant to someone like me who doesn't care about spaces.
![IMG_20221122_165927](https://user-images.githubusercontent.com/115653671/203309524-e122ccd4-020f-4c28-b3c8-4f34582b7b34.jpg)

### Describe the solution you'd like/描述你想要的解决方案

Hide the Now live bar.

**Comment by ianchb** [comment]
@Narayana2195 I suggest sending a pr instead of an issue
