### ISSUE TITLE
Doesn't block promoted tweets [Bug] 

### ISSUE THREAD

**Issue by nonetrix** [Dr-TSNG/TwiFucker#75]
### Steps to reproduce/复现步骤

1. Enable blocking promoted tweets
2. Restart
3. Doesn't block anything

### Expected behaviour/预期行为

1. Enable blocking promoted tweets
2. Actually blocks them

### Actual behaviour/实际行为

![Screenshot_20221123-002325](https://user-images.githubusercontent.com/45698918/203484154-07855e10-3ddb-432f-bda3-d0a66160603a.png)

### Xposed Module List/Xposed 模块列表

```Shell
1. Classic power menu
2. Notification shade transparency
3. Twitfucker
```

### TwiFucker version/TwiFucker 版本

1.7 release 

### Twitter version/Twitter 版本

9.65.5

### Android version/Android 版本

CalyxOS 4.2.7 based on Android 13

### Xposed Framework/Xposed 框架

LSPosed

### Framework version/框架版本

I don't understand, tell me how to get this information

### Version requirement/版本要求

Public release/beta version/公开发布/测试版

### Logs/日志

No logs

**Comment by JasonKhew96** [comment]
@nonetrix disable "Use legacy hook"
json hook is broken in this version

**Comment by HinataKato** [comment]
> @nonetrix disable "Use legacy hook" json hook is broken in this version

Even with the legacy hook disabled, it still doesn't work

**Comment by JasonKhew96** [comment]
fixed in 2bd0f8d4f37e8de8eca5b07aff419e33c4596510

**Comment by JasonKhew96** [comment]
> > @nonetrix disable "Use legacy hook" json hook is broken in this version
> 
> Even with the legacy hook disabled, it still doesn't work

@HinataKato try [CI build](https://github.com/Dr-TSNG/TwiFucker/actions/workflows/main.yml) ?
tested in `9.65.6-release.0`, it works just fine

**Comment by HinataKato** [comment]
> > > @nonetrix disable "Use legacy hook" json hook is broken in this version
> > 
> > 
> > Even with the legacy hook disabled, it still doesn't work
> 
> @HinataKato try [CI build](https://github.com/Dr-TSNG/TwiFucker/actions/workflows/main.yml) ? tested in `9.65.6-release.0`, it works just fine

Yep, it's working
