### ISSUE TITLE
[Bug] Download Button

### ISSUE THREAD

**Issue by xMostafax** [Dr-TSNG/TwiFucker#77]
### Steps to reproduce/复现步骤

The download button doesn't work for Twitter v 9.65.1 with latest CI build.

### Expected behaviour/预期行为

.

### Actual behaviour/实际行为

.

### Xposed Module List/Xposed 模块列表

```Shell
.
```

### TwiFucker version/TwiFucker 版本

V1.7.r123.3db3d33-release

### Twitter version/Twitter 版本

9.65.1

### Android version/Android 版本

12L

### Xposed Framework/Xposed 框架

LSPosed

### Framework version/框架版本

1.8.5

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

.

**Comment by JasonKhew96** [comment]
@xMostafax only latest stable release version of Twitter, this is why I put it in experimental section, this feature might not able to survive each Twitter version update

you can use old version of TwiFucker
