### ISSUE TITLE
[Feature Request] Hide "View" count

### ISSUE THREAD

**Issue by mangkoran** [Dr-TSNG/TwiFucker#84]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Recent Twitter update adds "View" count to tweets. It might be seen as "clutter"/"nonsense" for user that don't care about how much their tweets have been seen.

![Screenshot_20221223-201235_Twitter](https://user-images.githubusercontent.com/57625126/209341907-e69bbfc0-a92a-4240-90ad-038548915050.png)

### Describe the solution you'd like/描述你想要的解决方案

Option to hide "View" count.

### Additional context/其他信息

https://twitter.com/elonmusk/status/1605957811162054656

**Comment by MikuDroid** [comment]
yes please :( the analytics stats below tweet also make display a bit cramped than before, too much going on with numbers.

![Screenshot 2022-12-27 at 08-12-00 Elon Musk (@elonmusk) _ Twitter](https://user-images.githubusercontent.com/22476406/209596293-80a636b9-5f9f-4aa0-89fc-c3d6d6a6828c.png)
this is with tweak-new-twitter enabled 

![Screenshot 2022-12-27 at 08-12-20 Elon Musk (@elonmusk) _ Twitter](https://user-images.githubusercontent.com/22476406/209596347-92666e79-e489-4d86-a2c5-78b358e8fa22.png)
and this is not.

**Comment by SpyrosRai** [comment]
i second this, it's really annoying and inaccurate

**Comment by rodrigoswz** [comment]
Revanced has a patch for this

**Comment by JasonKhew96** [comment]
try using `Feature Switch` from TwiFucker v1.9, set `view_counts_public_visibility_enabled` to `false` (might not work in the future version).
There is no plan for this feature because Twitter constantly tweaking and changing view count feature.

**Comment by MikuDroid** [comment]
thanks, the workaround worked in v9.73.0

**Comment by mangkoran** [comment]
Thanks it works! I will close this ticket then.
