### ISSUE TITLE
[Feature Request] Revanced Patch Creation 

### ISSUE THREAD

**Issue by OshekharO** [Dr-TSNG/TwiFucker#94]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

Can you create patch for https://github.com/revanced/revanced-patches ? Like Remove promoted content , Remove promoted user, etc.

**Comment by Dr-TSNG** [comment]
No because there's already lspatch version

**Comment by JasonKhew96** [comment]
You can just use [LSPatch](https://github.com/LSPosed/LSPatch/) to embed Xposed module into apk for non-rooted Android device
We do distribute TwiFucker embedded apk in [Telegram Channel](https://t.me/TwiFucker)
