### ISSUE TITLE
[Feature Request] Expand timelines_translate_enabled to Lists

### ISSUE THREAD

**Issue by iLikeCake10** [Dr-TSNG/TwiFucker#95]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

timelines_translate_enabled only works in For you / Latest tweets feeds. Lists does not support this feature.

### Describe the solution you'd like/描述你想要的解决方案

Add timelines_translate_enabled support for Lists.

### Additional context/其他信息

![20230120_142037](https://user-images.githubusercontent.com/122379215/213654814-46bd7530-3379-4c5b-9e7d-48d61af166ad.jpg)

**Comment by JasonKhew96** [comment]
Feature flags is provided by Twitter itself, those features most likely in development, or maybe there is a flag that can enable translate feature for _Lists_.
You can view those flags in Twitter apk (`res/raw/feature_switch_manifest`)
