### ISSUE TITLE
Option to default to Following tab on launch

### ISSUE THREAD

**Issue by kobitate** [Dr-TSNG/TwiFucker#97]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Twitter defaults to algorithm feed For You tab, displaying tweets in non-chronological order and from accounts I don't follow. 

### Describe the solution you'd like/描述你想要的解决方案

Would like to have an option to default to Following tab on launch. 

### Additional context/其他信息

Could also add the option to hide the For You tab.

**Comment by iLikeCake10** [comment]
![Screenshot_2023-01-22-13-53-56-50_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/122379215/213906956-129c9174-1e85-4916-8d47-1f2b6aaa7d53.jpg)
Twitter is already working on something similar to this. I could get behind the idea of hiding the For you tab, though.

**Comment by Eiskrem** [comment]
Yes the following/home tab needs to be the default at app startup. Also where did Elon say this? Got tweet link?

**Comment by iLikeCake10** [comment]
[It's already rolling out, coming soon for Android](https://twitter.com/TwitterSupport/status/1617964019666800640)
